"""Paths, pools, regex patterns, and tunables for the FirstSky app."""
from __future__ import annotations

__version__ = "1.0.0"

import os
import re
from pathlib import Path
from typing import Any

import requests

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------

# ``constants.py`` lives at ``folders/resyco/constants.py`` — repo root is two levels up from ``resyco/``.
ROOT = Path(__file__).resolve().parent.parent.parent
UNIVERSAL_DIR = Path(__file__).resolve().parent.parent
ASSETS = UNIVERSAL_DIR / "assets"
OUTPUT = ROOT / "output"
OUTPUT_DIR = OUTPUT  # FFV outputs
MUSIC = UNIVERSAL_DIR / "music"
DISCLAIMER_MP3 = UNIVERSAL_DIR / "Disclaimer.mp3"
LEGACY_UNIVERSAL_DIR = ROOT / "F0LD3R$"
LEGACY_UNIVERSAL_ALT = ROOT / "universal"
LEGACY_ASSETS = ROOT / "assets"
# Previous default was ``folders/output``; migrate into ``OUTPUT`` on startup when present.
LEGACY_OUTPUT_IN_FOLDERS = UNIVERSAL_DIR / "output"
LEGACY_MUSIC = ROOT / "Music"
TEMP = ASSETS / "temp"
TTSPEECH_DIR = ASSETS / "ttspeech"
USED_STORY_DB_FILE = OUTPUT / "used_stories.db"
LEGACY_USED_STORY_IDS_FILE = OUTPUT / "used_story_ids.txt"
LEGACY_USED_STORY_MAP_FILE = OUTPUT / "used_story_map.tsv"
PRESETS_DIR = UNIVERSAL_DIR / "presets"
DASHBOARD_DIR = OUTPUT / "dashboard"
DEFAULT_QUEUE_FILE = UNIVERSAL_DIR / "queue.txt"
EXTRAS_LOG_DIR = OUTPUT / "extras_logs"

# Extra pools (kept separate so the main list stays readable).
_EXTRA_STORY_SUBREDDITS: tuple[str, ...] = (
    "LifeAdvice",
    "Needafriend",
    "offmychest",
    "TrueOffMyChest",
    "UnsentLetters",
    "confession",
    "Confessions",
    "TrueConfessions",
    "self",
    "selfhelp",
    "getmotivated",
    "Mindfulness",
    "Stoicism",
    "Meditation",
    "sleep",
    "ADHD",
    "OCD",
    "BPD",
    "raisedbynarcissists",
    "justnoMIL",
    "JustNoSO",
    "Divorce",
    "SurvivingInfidelity",
    "DeadBedrooms",
    "longdistance",
    "LDR",
    "Widowers",
    "Widow",
    "BabyBumps",
    "beyondthebump",
    "Mommit",
    "Daddit",
    "Parenting",
    "stepparents",
    "coparenting",
    "povertyfinance",
    "EatCheapAndHealthy",
    "mealprep",
    "slowcooking",
    "InstantPot",
    "Coffee",
    "tea",
    "HomeMaintenance",
    "HomeImprovement",
    "HomeDecor",
    "Organization",
    "declutter",
    "BuyItForLife",
    "Anticonsumption",
    "zerowaste",
    "sustainability",
    "climate",
    "environment",
    "urbanplanning",
    "bicycling",
    "running",
    "Swimming",
    "bodyweightfitness",
    "xxfitness",
    "loseit",
    "progresspics",
    "PlantBasedDiet",
    "vegan",
    "vegetarian",
    "nutrition",
    "Supplements",
    "SkincareAddiction",
    "malefashionadvice",
    "femalefashionadvice",
    "curlyhair",
    "HaircareScience",
    "learnprogramming",
    "webdev",
    "Python",
    "javascript",
    "golang",
    "rust",
    "csharp",
    "java",
    "learnjava",
    "sysadmin",
    "linux",
    "ubuntu",
    "debian",
    "selfhosted",
    "homelab",
    "HomeNetworking",
    "buildapc",
    "hardware",
    "MechanicalKeyboards",
    "pcmasterrace",
    "apple",
    "iphone",
    "android",
    "privacy",
    "cybersecurity",
    "netsec",
    "Entrepreneur",
    "smallbusiness",
    "startups",
    "SideProject",
    "passive_income",
    "remotework",
    "UKPersonalFinance",
    "AusFinance",
    "CanadianInvestor",
    "EuropeFIRE",
    "BestofRedditorUpdates",
    "AmItheAsshole",
    "relationship_advice",
    "TalesFromYourServer",
    "TalesFromTheFrontDesk",
    "TalesFromTheCustomer",
    "MaliciousCompliance",
    "pettyrevenge",
    "ProRevenge",
    "EntitledPeople",
    "ChoosingBeggars",
    "IDontWorkHereLady",
    "LetsNotMeet",
    "creepyencounters",
    "TrueCrime",
    "UnresolvedMysteries",
)

_EXTRA_BROLL_SUBREDDITS: tuple[str, ...] = (
    "mesmerizing",
    "trippy",
    "replications",
    "Simulated",
    "physicsgifs",
    "biologygifs",
    "geometryisneat",
    "FractalGifs",
    "perfectloops",
    "Cinemagraphs",
    "HighQualityGifs",
    "reactiongifs",
    "gifsthatkeepongiving",
    "TheDepthsBelow",
    "WeatherGifs",
    "Stormchasing",
    "volcanoes",
    "geology",
    "EarthPorn",
    "CityPorn",
    "InfrastructurePorn",
    "BridgePorn",
    "TrainPorn",
    "aviationgifs",
    "MilitaryGfys",
    "TankPorn",
    "ArtisanBread",
    "Breadit",
    "pizza",
    "steak",
    "BBQ",
    "smoking",
    "fermentation",
    "cheesemaking",
    "icecreamery",
    "cocktails",
    "espresso",
    "latteart",
    "KnifeSkills",
    "castiron",
    "slowcooking",
    "StreetFoodArtists",
    "WatchPeopleDieInside",
    "Instantregret",
    "Wellthatsucks",
    "nonononoyes",
    "yesyesyesno",
    "maybemaybemaybe",
    "AccidentalRenaissance",
    "AccidentalWesAnderson",
    "MostBeautiful",
    "MostInteresting",
    "NatureIsMetal",
    "hardcoreaww",
    "bigboye",
    "IllegallySmolCats",
    "WhatsWrongWithYourDog",
    "WhatsWrongWithYourCat",
    "StartledCats",
    "CatsWhoYell",
    "CatsInSinks",
    "CatsOnKeyboards",
    "dogswithjobs",
    "AnimalsBeingJerks",
    "AnimalsBeingDerps",
    "likeus",
    "NatureBrutality",
    "HeavySeas",
    "kitesurfing",
    "wingfoil",
    "Slackline",
    "Parkour",
    "freerunning",
    "BMX",
    "skateboarding",
    "surfing",
    "longboarding",
    "FixedGearBicycle",
    "gravelcycling",
    "MTB",
    "IdiotsFightingThings",
    "HumansBeingBros",
    "MadeMeSmile",
    "UpliftingNews",
)

STORY_SUBREDDITS = [
    "AskReddit",
    "NoStupidQuestions",
    "TooAfraidToAsk",
    "explainlikeimfive",
    "Advice",
    "internetparents",
    "DecidingToBeBetter",
    "selfimprovement",
    "productivity",
    "getdisciplined",
    "socialskills",
    "confidence",
    "anxiety",
    "depression",
    "mentalhealth",
    "CPTSD",
    "autism",
    "loneliness",
    "griefsupport",
    "stopdrinking",
    "leaves",
    "pornfree",
    "nosurf",
    "simpleliving",
    "minimalism",
    "Frugal",
    "personalfinance",
    "FinancialPlanning",
    "studentloans",
    "careerguidance",
    "jobs",
    "resumes",
    "findapath",
    "careeradvice",
    "work",
    "relationships",
    "dating",
    "marriage",
    "breakup",
    "friendship",
    "family",
    "parenting",
    "NewParents",
    "singlemoms",
    "SingleDads",
    "blendedfamilies",
    "TwoXChromosomes",
    "CasualConversation",
    "rant",
    "venting",
    "unpopularopinion",
    "changemyview",
    "AmIWrong",
    "legaladviceofftopic",
    "books",
    "movies",
    "television",
    "gaming",
    "history",
    "philosophy",
    "psychology",
    "askscience",
    "AskHistorians",
    "asksocialscience",
    "askphilosophy",
    "science",
    "technology",
    "Futurology",
    "space",
    "Astronomy",
    "cooking",
    "baking",
    "gardening",
    "woodworking",
    "photography",
    "writing",
    "screenwriting",
    "Journaling",
    "poetry",
    "fanfiction",
    "worldbuilding",
    "conlangs",
    "mapmaking",
    "tabletoprpg",
    "DnD",
    "Pathfinder_RPG",
    "boardgames",
    "chess",
    "fitness",
    "running",
    "cycling",
    "hiking",
    "camping",
    "travel",
    "solotravel",
    "digitalnomad",
    "vanlife",
    "medschool",
    "lawschool",
] + list(_EXTRA_STORY_SUBREDDITS)
# Reddit-hosted video (v.redd.it) for background; merged and de-duped in ``fetch_asmr_video_posts``.
BROLL_SUBREDDITS = [
    "oddlysatisfying",
    "satisfying",
    "ASMR",
    "unintentionalASMR",
    "ArtisanVideos",
    "DidntKnowIWantedThat",
    "BetterEveryLoop",
    "PowerwashingPorn",
    "SoapCarving",
    "ThingsCutInHalfPorn",
    "Restorationvideos",
    "MachinePorn",
    "ManufacturingPorn",
    "engineering",
    "EngineeringPorn",
    "blacksmithing",
    "metalworking",
    "Welding",
    "knifemaking",
    "Carpentry",
    "woodworking",
    "CNC",
    "3Dprinting",
    "pottery",
    "ResinCasting",
    "GlassBlowing",
    "pourpainting",
    "cakedecorating",
    "Sewing",
    "Crochet",
    "crossstitch",
    "papercraft",
    "lego",
    "modelmakers",
    "DIY",
    "howitsmade",
    "specializedtools",
    "FastWorkers",
    "heavyequipment",
    "laserCleaningPorn",
    "lasers",
    "mechanical_gifs",
    "chemicalreactiongifs",
    "educationalgifs",
    "Damnthatsinteresting",
    "interestingasfuck",
    "nextfuckinglevel",
    "beamazed",
    "PraiseTheCameraMan",
    "PerfectTiming",
    "NatureIsFuckingLit",
    "NatureVideos",
    "NatureGif",
    "CampingandHiking",
    "Fishing",
    "Kayaking",
    "sailing",
    "scuba",
    "paragliding",
    "skydiving",
    "snowboarding",
    "bouldering",
    "climbing",
    "Mountaineering",
    "aviation",
    "drones",
    "helicopters",
    "Formula1",
    "Motorsports",
    "motorcycles",
    "CarPorn",
    "Roadcam",
    "Dashcam",
    "IdiotsInCars",
    "AnimalsBeingBros",
    "AnimalsBeingGeniuses",
    "BabyAnimals",
    "aww",
    "eyebleach",
    "CatTaps",
    "foxes",
    "Zoomies",
    "AbsoluteUnits",
    "ContagiousLaughter",
    "JustGuysBeingDudes",
    "woahdude",
    "BlackMagicFuckery",
    "gifrecipes",
    "foodvideos",
    "DessertPorn",
    "StupidFood",
    "Aquariums",
    "astrophotography",
    "space",
    "FractalPorn",
    "ProductPorn",
    "StreetArtVideos",
    "ConvenientCop",
    "Submechanophobia",
    "thalassophobia",
] + list(_EXTRA_BROLL_SUBREDDITS)
INCOMPETECH_MUSIC_PAGE = "https://incompetech.com/music/royalty-free/music.html"
INCOMPETECH_FULL_LIST = "https://incompetech.com/music/royalty-free/full_list.php"
NARRATION_SPEED = 0.80
# Edge ``rate`` (SSML): slightly slower synthesis = clearer consonants. ``PTK_EDGE_TTS_RATE=0`` → +0%.
EDGE_TTS_DEFAULT_RATE = "-6%"
# After TTS: gentle speech EQ + high-pass, then ``atempo``. Set ``PTK_NARRATION_CLEAR_FILTERS=0`` to skip EQ.
NARRATION_MIX_VOICE_GAIN = 1.12
NARRATION_MIX_MUSIC_GAIN = 0.28
# Microsoft Edge neural voices (``pip install edge-tts``; set PTK_EDGE_TTS=1 or PTK_TTS_ENGINE=edge).
EDGE_TTS_ENGLISH_NEURAL: tuple[str, ...] = (
    "en-US-GuyNeural",
    "en-US-AriaNeural",
    "en-US-JennyNeural",
    "en-US-JennyMultilingualNeural",
    "en-US-DavisNeural",
    "en-US-AmberNeural",
    "en-US-AnaNeural",
    "en-US-AshleyNeural",
    "en-US-BrandonNeural",
    "en-US-ChristopherNeural",
    "en-US-CoraNeural",
    "en-US-ElizabethNeural",
    "en-US-EricNeural",
    "en-US-JacobNeural",
    "en-US-JaneNeural",
    "en-US-JasonNeural",
    "en-US-MichelleNeural",
    "en-US-MonicaNeural",
    "en-US-NancyNeural",
    "en-US-RogerNeural",
    "en-US-RyanNeural",
    "en-US-SaraNeural",
    "en-US-SteffanNeural",
    "en-US-TonyNeural",
    "en-GB-SoniaNeural",
    "en-GB-RyanNeural",
    "en-GB-LibbyNeural",
    "en-GB-MaisieNeural",
    "en-GB-ThomasNeural",
    "en-AU-NatashaNeural",
    "en-AU-WilliamNeural",
    "en-CA-ClaraNeural",
    "en-CA-LiamNeural",
    "en-IE-EmilyNeural",
    "en-IE-ConnorNeural",
    "en-IN-NeerjaNeural",
    "en-IN-PrabhatNeural",
    "en-NZ-MollyNeural",
    "en-PH-RosaNeural",
    "en-PH-JamesNeural",
    "en-SG-LunaNeural",
    "en-SG-WayneNeural",
    "en-ZA-LeahNeural",
    "en-ZA-LukeNeural",
    "en-US-AndrewMultilingualNeural",
    "en-US-EmmaMultilingualNeural",
    "en-US-BrianMultilingualNeural",
    "en-US-AvaMultilingualNeural",
    "en-US-AndrewNeural",
    "en-US-EmmaNeural",
    "en-US-BrianNeural",
    "en-US-AvaNeural",
    "en-US-AlloyTurboMultilingualNeural",
    "en-US-AndrewTurboMultilingualNeural",
    "en-US-EmmaTurboMultilingualNeural",
    "en-US-BrianMultilingualNeuralHD",
    "en-US-AvaMultilingualNeuralHD",
    "en-GB-AdaMultilingualNeural",
    "en-GB-OllieMultilingualNeural",
    "en-GB-AdaNeural",
    "en-GB-OllieNeural",
    "en-AU-AnnetteNeural",
    "en-AU-CarlyNeural",
    "en-AU-DarrenNeural",
    "en-AU-DuncanNeural",
    "en-AU-ElsieNeural",
    "en-AU-FreyaNeural",
    "en-AU-JoanneNeural",
    "en-AU-KenNeural",
    "en-CA-HeatherNeural",
    "en-CA-LindaNeural",
    "en-CA-RichardNeural",
    "en-IN-PriyaNeural",
    "en-IN-AaravNeural",
    "en-IE-EimearNeural",
    "en-IE-EoinNeural",
    "en-NZ-MitchellNeural",
    "en-NZ-MiaNeural",
    "en-NG-AbeoNeural",
    "en-NG-EzinneNeural",
    "en-HK-SamNeural",
    "en-HK-YanNeural",
    "en-KE-AsiliaNeural",
    "en-KE-ChilembaNeural",
    "en-TZ-ElimuNeural",
    "en-TZ-ImaniNeural",
    "en-US-AdamMultilingualNeural",
    "en-US-AmandaMultilingualNeural",
    "en-US-DerekMultilingualNeural",
    "en-US-DustinMultilingualNeural",
    "en-US-EvelynMultilingualNeural",
    "en-US-LewisMultilingualNeural",
    "en-US-LolaMultilingualNeural",
    "en-US-PhoebeMultilingualNeural",
    "en-US-RyanMultilingualNeural",
    "en-US-SamuelMultilingualNeural",
    "en-US-SerenaMultilingualNeural",
    "en-US-SteffanMultilingualNeural",
)
EDGE_TTS_MAX_CHUNK = 2800
# If the chosen voice 404s or is region-locked, try these in order (stable Edge-tts ids).
EDGE_TTS_FALLBACK_VOICES: tuple[str, ...] = (
    "en-US-JennyNeural",
    "en-US-AriaNeural",
    "en-US-DavisNeural",
    "en-US-SaraNeural",
    "en-US-EricNeural",
)


def _edge_tts_voice_attempt_order(preferred: str) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for v in (preferred, *EDGE_TTS_FALLBACK_VOICES):
        k = v.casefold()
        if k in seen:
            continue
        seen.add(k)
        out.append(v)
    return out


MIN_POST_CHARS = 50
_EXTRA_AD_SOFT_MARKERS: tuple[str, ...] = (
    "paid post",
    "paid placement",
    "native ad",
    "advertorial",
    "commission",
    "commission link",
    "referral",
    "referral link",
    "ref link",
    "amazon associate",
    "amazon affiliate",
    "impact radius",
    "shareasale",
    "cj affiliate",
    "rakuten",
    "awin",
    "partner link",
    "sponsored segment",
    "sponsored by",
    "brought to you by",
    "thanks to our sponsor",
    "message from our sponsor",
    "this episode is sponsored",
    "today's sponsor",
    "use my link",
    "my link below",
    "link below",
    "links below",
    "discount code",
    "promo link",
    "flash sale",
    "early bird",
    "preorder",
    "pre-order",
    "launch week",
    "product launch",
    "new drop",
    "restock",
    "inventory",
    "sku",
    "checkout",
    "cart",
    "add to cart",
    "free shipping",
    "bundle deal",
    "two for one",
    "bogo",
    "subscription box",
    "newsletter signup",
    "email list",
    "mailing list",
    "waitlist",
    "beta access",
    "founders pricing",
    "lifetime deal",
    "annual plan",
    "monthly plan",
    "upgrade now",
    "go premium",
    "unlock",
    "exclusive offer",
    "members only",
    "patrons only",
    "patreon",
    "onlyfans",
    "tip jar",
    "support me on",
    "buy me a coffee",
    "ko-fi",
    "cashapp",
    "venmo",
    "paypal",
    "stripe checkout",
    "invoice",
    "consultation booking",
    "book a call",
    "schedule a demo",
)
_EXTRA_AD_CTA_MARKERS: tuple[str, ...] = (
    "tap here",
    "tap the link",
    "swipe up",
    "link in comments",
    "pinned comment",
    "first link",
    "second link",
    "bio link",
    "tree link",
    "linktree",
    "apply now",
    "join now",
    "get started",
    "start free trial",
    "try free",
    "claim offer",
    "redeem",
    "enter code",
    "use my code",
    "at checkout",
    "limited stock",
    "while supplies last",
    "act fast",
    "don't miss",
    "last chance",
    "closing soon",
    "doors close",
    "enroll today",
    "register here",
    "rsvp",
    "book now",
    "reserve your spot",
    "add to wishlist",
    "notify me",
    "join the waitlist",
    "get notified",
    "download the app",
    "install now",
    "scan qr",
    "qr code",
    "text me",
    "message me",
    "inquire within",
    "slide into dms",
    "follow for part",
    "full video on",
    "watch on youtube",
    "subscribe on youtube",
    "hit subscribe",
    "turn notifications on",
    "bell icon",
)
AD_SOFT_MARKERS: tuple[str, ...] = (
    "sponsored",
    "sponsor",
    "advertisement",
    "promoted",
    "partnered",
    "paid partnership",
    "affiliate",
    "affiliate link",
    "ad break",
    "my shop",
    "my store",
    "etsy shop",
    "merch",
    "merch drop",
    "promo",
    "promotion",
    "discount",
    "deal",
    "giveaway",
    "sweepstakes",
    "limited time",
    "limited offer",
    "brand deal",
    "collab",
    "collaboration",
) + _EXTRA_AD_SOFT_MARKERS
AD_CTA_MARKERS: tuple[str, ...] = (
    "use code",
    "promo code",
    "coupon code",
    "code:",
    "buy now",
    "shop now",
    "order now",
    "check it out",
    "sign up",
    "subscribe",
    "download now",
    "click the link",
    "link in bio",
    "dm me",
    "visit my",
) + _EXTRA_AD_CTA_MARKERS
_AD_SOFT_PATTERN = re.compile(
    r"\b(?:"
    + "|".join(re.escape(w) for w in sorted(AD_SOFT_MARKERS, key=len, reverse=True))
    + r")\b",
    re.IGNORECASE,
)
_AD_CTA_PATTERN = re.compile(
    r"(?:"
    + "|".join(re.escape(w) for w in sorted(AD_CTA_MARKERS, key=len, reverse=True))
    + r")",
    re.IGNORECASE,
)
_AD_URL_PATTERN = re.compile(r"(?:https?://|www\.)", re.IGNORECASE)

# Whole-word match (case-insensitive) on title + body; matching posts are never candidates.
_EXTRA_NSFW_BLOCKED_WORDS: tuple[str, ...] = (
    "shit",
    "bullshit",
    "asshole",
    "bastard",
    "cunt",
    "twat",
    "clit",
    "clitoris",
    "erotic",
    "erotica",
    "hentai",
    "nsfw",
    "onlyfans",
    "camgirl",
    "camboy",
    "stripper",
    "stripping",
    "escort",
    "prostitute",
    "prostitution",
    "brothel",
    "gangbang",
    "threesome",
    "orgy",
    "bdsm",
    "bondage",
    "dominatrix",
    "submissive",
    "fisting",
    "deepthroat",
    "creampie",
    "bukkake",
    "milf",
    "dilf",
    "lolita",
    "jailbait",
    "childporn",
    "grooming",
    "bestiality",
    "zoophilia",
    "necrophilia",
    "snuff",
    "gooning",
    "goon",
    "edging",
    "jerkoff",
    "jackoff",
    "cumshot",
    "facial",
    "strap-on",
    "strapon",
    "buttplug",
    "vibrator",
    "fleshlight",
    "only fans",
    "fansly",
    "chaturbate",
    "pornhub",
    "xvideos",
    "xhamster",
    "redtube",
    "brazzers",
    "playboy",
    "penthouse",
    "hustler",
    "strip club",
    "happy ending",
    "rub and tug",
    "glory hole",
    "gloryhole",
    "cumslut",
    "slutty",
    "whoring",
    "hooker",
    "pimp",
    "pimping",
    "trafficking",
    "sexual assault",
    "sexual violence",
    "revenge porn",
    "deepfake porn",
    "upskirt",
    "downblouse",
    "peeping",
    "voyeur",
    "exhibitionist",
    "flashing",
    "groping",
    "fondling",
    "molested",
    "statutory",
    "underage sex",
    "minor sex",
)
NSFW_BLOCKED_WORDS: tuple[str, ...] = (
    "fuck",
    "bitch",
    "sex",
    "cock",
    "dick",
    "fucking",
    "motherfucker",
    "whore",
    "slut",
    "porn",
    "pornography",
    "nude",
    "nudes",
    "nudity",
    "boobs",
    "tits",
    "pussy",
    "vagina",
    "penis",
    "cum",
    "cumming",
    "orgasm",
    "horny",
    "fetish",
    "anal",
    "blowjob",
    "handjob",
    "rimjob",
    "dildo",
    "masturbate",
    "masturbation",
    "incest",
    "molest",
    "molestation",
    "rape",
    "raped",
    "rapist",
    "pedophile",
    "pedophilia",
) + _EXTRA_NSFW_BLOCKED_WORDS
_NSFW_BLOCKED_PATTERN = re.compile(
    r"\b(?:"
    + "|".join(re.escape(w) for w in sorted(NSFW_BLOCKED_WORDS, key=len, reverse=True))
    + r")\b",
    re.IGNORECASE,
)

# Title + body: if matched, prepend ``DISCLAIMER_MP3`` to final audio and lead the video with black frames.
_EXTRA_DISCLAIMER_TRIGGER_WORDS: tuple[str, ...] = (
    "polyamory",
    "polyamorous",
    "poly",
    "open relationship",
    "swinging",
    "swinger",
    "aromantic",
    "demisexual",
    "graysexual",
    "two-spirit",
    "twospirit",
    "agender",
    "bigender",
    "demiboy",
    "demigirl",
    "gender dysphoria",
    "gender euphoria",
    "gender affirming",
    "top surgery",
    "bottom surgery",
    "hormone therapy",
    "hrt",
    "estrogen",
    "testosterone",
    "blockers",
    "puberty blockers",
    "they them",
    "they/them",
    "she her",
    "he him",
    "xe xem",
    "ze zir",
    "neopronouns",
    "misgender",
    "misgendering",
    "dead name",
    "outing",
    "outed",
    "closeted",
    "in the closet",
    "pride parade",
    "pride month",
    "drag queen",
    "drag king",
    "ballroom",
    "sapphic",
    "achillean",
    "wlw",
    "enby",
)
DISCLAIMER_TRIGGER_WORDS: tuple[str, ...] = (
    "gay",
    "lesbian",
    "trans",
    "transgender",
    "bisexual",
    "bi",
    "pansexual",
    "asexual",
    "queer",
    "lgbt",
    "lgbtq",
    "lgbtqia",
    "nonbinary",
    "non-binary",
    "genderfluid",
    "genderqueer",
    "intersex",
    "pronouns",
    "same-sex",
    "homosexual",
    "coming out",
    "transition",
    "deadname",
    "chosen name",
) + _EXTRA_DISCLAIMER_TRIGGER_WORDS
_DISCLAIMER_TRIGGER_PATTERN = re.compile(
    r"\b(?:"
    + "|".join(re.escape(w) for w in sorted(DISCLAIMER_TRIGGER_WORDS, key=len, reverse=True))
    + r")\b",
    re.IGNORECASE,
)
DEFAULT_DISCLAIMER_TTS_TEXT = (
    "Warning. This video may include references to universally disturbing adult content, "
    "including sexual violence, exploitation, abuse, coercion, or non-consensual acts. "
    "Viewer discretion is strongly advised."
)
HOOKS_ENABLED = os.environ.get("PTK_HOOKS", "1").strip().lower() in ("1", "true", "yes", "on")
HOOK_MAX_CHARS = 96
_EXTRA_HOOK_POWER_WORDS: tuple[str, ...] = (
    "insane",
    "wild",
    "update",
    "plot",
    "karma",
    "justice",
    "petty",
    "nuclear",
    "toxic",
    "blocked",
    "ghosted",
    "leaked",
    "screenshot",
    "evidence",
    "lawyer",
    "court",
    "police",
    "fired",
    "quit",
    "walked",
    "out",
    "ruined",
    "destroyed",
    "never",
    "again",
    "warning",
    "red",
    "flag",
    "final",
    "boss",
    "ceo",
    "hr",
    "neighbor",
    "roommate",
    "mother",
    "father",
    "inlaw",
    "cheating",
    "affair",
    "divorce",
    "custody",
    "inheritance",
    "will",
    "money",
    "debt",
    "scam",
    "fraud",
    "stolen",
    "caught",
    "camera",
    "doorbell",
    "ring",
    "texts",
    "dm",
    "group",
    "chat",
    "family",
    "groupchat",
    "exploded",
    "meltdown",
    "breakdown",
    "panic",
    "therapy",
    "no",
    "contact",
    "boundaries",
    "ultimatum",
    "last",
    "straw",
    "bombshell",
    "confession",
    "hidden",
    "years",
    "decades",
    "finally",
    "today",
    "tonight",
    "yesterday",
    "tomorrow",
)
HOOK_POWER_WORDS = (
    "truth",
    "secret",
    "caught",
    "betrayed",
    "exposed",
    "worst",
    "crazy",
    "unbelievable",
    "shocking",
    "regret",
    "revenge",
    "proof",
    "finale",
    "twist",
) + _EXTRA_HOOK_POWER_WORDS
_EXTRA_HOOK_STOPWORDS: frozenset[str] = frozenset(
    {
        "also",
        "even",
        "ever",
        "still",
        "again",
        "once",
        "twice",
        "maybe",
        "perhaps",
        "rather",
        "quite",
        "very",
        "really",
        "actually",
        "basically",
        "literally",
        "obviously",
        "probably",
        "definitely",
        "certainly",
        "anyway",
        "though",
        "however",
        "therefore",
        "otherwise",
        "instead",
        "unless",
        "until",
        "since",
        "without",
        "within",
        "among",
        "between",
        "against",
        "during",
        "through",
        "across",
        "around",
        "another",
        "other",
        "others",
        "someone",
        "anyone",
        "everyone",
        "nobody",
        "nothing",
        "something",
        "anything",
        "everything",
        "somewhere",
        "anywhere",
        "everywhere",
        "already",
        "almost",
        "always",
        "never",
        "sometimes",
        "often",
        "usually",
        "being",
        "having",
        "doing",
        "going",
        "getting",
        "making",
        "taking",
        "giving",
        "coming",
        "looking",
        "feeling",
        "thinking",
        "trying",
        "wanted",
        "needs",
        "need",
        "said",
        "says",
        "tell",
        "told",
        "asked",
        "asks",
        "know",
        "knew",
        "think",
        "thought",
        "seem",
        "seems",
        "seemed",
        "like",
        "liked",
        "want",
        "wants",
        "went",
        "come",
        "came",
        "see",
        "saw",
        "look",
        "looks",
        "looked",
        "way",
        "ways",
        "day",
        "days",
        "year",
        "years",
        "time",
        "times",
        "week",
        "weeks",
        "month",
        "months",
        "thing",
        "things",
        "stuff",
        "lot",
        "lots",
        "bit",
        "kind",
        "sort",
        "type",
        "part",
        "parts",
        "place",
        "places",
        "people",
        "person",
        "guys",
        "girls",
        "man",
        "men",
        "woman",
        "women",
        "kid",
        "kids",
        "child",
        "children",
    }
)
HOOK_STOPWORDS = {
    "the",
    "and",
    "for",
    "that",
    "with",
    "this",
    "from",
    "have",
    "were",
    "what",
    "when",
    "your",
    "just",
    "about",
    "they",
    "them",
    "their",
    "there",
    "would",
    "could",
    "should",
    "into",
    "been",
    "after",
    "before",
    "because",
    "while",
    "where",
    "which",
    "then",
} | _EXTRA_HOOK_STOPWORDS


def _story_contains_nsfw_blocked_words(post: dict[str, Any]) -> bool:
    blob = f"{post.get('title') or ''}\n{post.get('selftext') or ''}"
    return _NSFW_BLOCKED_PATTERN.search(blob) is not None


def _story_needs_disclaimer_audio(post: dict[str, Any]) -> bool:
    blob = f"{post.get('title') or ''}\n{post.get('selftext') or ''}"
    return _DISCLAIMER_TRIGGER_PATTERN.search(blob) is not None


def _story_looks_advertisement(raw_post: dict[str, Any]) -> bool:
    title = str(raw_post.get("title") or "")
    body = str(raw_post.get("selftext") or "")
    flair = str(raw_post.get("link_flair_text") or "")
    url = str(raw_post.get("url") or "")
    blob = f"{title}\n{body}\n{flair}\n{url}".strip()
    low = blob.lower()

    # Hard markers: treat as ad immediately.
    if raw_post.get("promoted"):
        return True
    if str(raw_post.get("distinguished") or "").strip().lower() == "promoted":
        return True
    if "affiliate link" in low or "paid partnership" in low or "link in bio" in low:
        return True

    soft_hits = len(_AD_SOFT_PATTERN.findall(blob))
    cta_hits = len(_AD_CTA_PATTERN.findall(blob))
    url_hits = len(_AD_URL_PATTERN.findall(blob))

    score = (soft_hits * 1.0) + (cta_hits * 1.3) + (url_hits * 0.7)
    # A common ad pattern: CTA + external links.
    if cta_hits >= 1 and url_hits >= 1:
        score += 1.2
    # Very link-heavy selftext is typically promotional.
    if url_hits >= 3:
        score += 1.0
    return score >= 2.6


# Enough depth to find long self-posts; early exit once we have enough candidates.
FAST_RENDER_MODE = os.environ.get("PTK_FAST", "1").strip().lower() in ("1", "true", "yes", "on")
AGGRESSIVE_MODE = os.environ.get("PTK_AGGRESSIVE", "1").strip().lower() in ("1", "true", "yes", "on")
REDDIT_PAGES_PER_SUB = 2 if FAST_RENDER_MODE else 4
REQUEST_PAUSE_SEC = 0.20 if FAST_RENDER_MODE else 0.35
MIN_STORY_CANDIDATES_STOP = 24 if FAST_RENDER_MODE else 45
STORY_MAX_SUBS_PER_RUN = 28 if FAST_RENDER_MODE else 90
STORY_FETCH_BUDGET_SEC = 55 if FAST_RENDER_MODE else 220
X264_PRESET = "ultrafast" if FAST_RENDER_MODE else "veryfast"
X264_CRF_SUBS = "27" if FAST_RENDER_MODE else "23"
X264_CRF_BG = "30" if FAST_RENDER_MODE else "26"
OUTPUT_W = 576 if FAST_RENDER_MODE and AGGRESSIVE_MODE else (720 if FAST_RENDER_MODE else 1080)
OUTPUT_H = 1024 if FAST_RENDER_MODE and AGGRESSIVE_MODE else (1280 if FAST_RENDER_MODE else 1920)
OUTPUT_FPS = 24 if FAST_RENDER_MODE and AGGRESSIVE_MODE else 30
BROLL_PAGES_PER_SUB = 1 if FAST_RENDER_MODE else 2
BROLL_MAX_SUBS_PER_RUN = 20 if FAST_RENDER_MODE else 60
BROLL_TARGET_POSTS = 90 if FAST_RENDER_MODE else 220
BROLL_FETCH_BUDGET_SEC = 50 if FAST_RENDER_MODE else 180
BROLL_BUILD_BUDGET_SEC = 110 if FAST_RENDER_MODE else 420
BROLL_MIN_UNIQUE_CLIPS = 2 if FAST_RENDER_MODE else 3

# Random UA per request without blocking (fake_useragent often hangs on first use while updating data).
_EXTRA_BROWSER_USER_AGENTS: tuple[str, ...] = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.142 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.5; rv:127.0) Gecko/20100101 Firefox/127.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0",
    "Mozilla/5.0 (iPad; CPU OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.70 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 14; SM-S928B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 13; moto g power) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Brave/124",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Brave/124",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Vivaldi/6.7",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 AVG/123",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Avast/123",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 PTST/240115.140547",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (PlayStation; PlayStation 5/9.00) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15",
    "Mozilla/5.0 (Nintendo Switch; WifiWebAuthApplet) AppleWebKit/601.6 (KHTML, like Gecko) NF/6.0.1.15.3 NintendoBrowser/5.1.0.20309",
    "Mozilla/5.0 (SMART-TV; Linux; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/108.0.5359.1 TV Safari/537.36",
    "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.14 Chrome/87.0.4280.144 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
)
_EXTRA_SENTIMENT_POS_WORDS: tuple[str, ...] = (
    "joy",
    "relieved",
    "proud",
    "grateful",
    "blessed",
    "excited",
    "hopeful",
    "peace",
    "calm",
    "safe",
    "supported",
    "validated",
    "closure",
    "healing",
    "progress",
    "win",
    "fixed",
    "solved",
    "okay",
    "fine",
    "nice",
    "lovely",
    "sweet",
    "kind",
    "fair",
    "respect",
    "trust",
    "honest",
    "apology",
    "forgave",
    "forgiven",
    "reconcile",
    "together",
    "family",
    "friends",
    "helped",
    "therapy",
    "growth",
)
_EXTRA_SENTIMENT_NEG_WORDS: tuple[str, ...] = (
    "panic",
    "depressed",
    "miserable",
    "devastated",
    "heartbroken",
    "lonely",
    "ashamed",
    "guilty",
    "regret",
    "resent",
    "bitter",
    "jealous",
    "paranoid",
    "triggered",
    "trauma",
    "ptsd",
    "abandon",
    "ghosted",
    "ignored",
    "humiliated",
    "embarrassed",
    "worthless",
    "hopeless",
    "exhausted",
    "burnout",
    "stress",
    "overwhelmed",
    "rage",
    "furious",
    "disgusted",
    "betrayal",
    "cheating",
    "lies",
    "manipulate",
    "gaslight",
    "threat",
    "violence",
    "unsafe",
)
_EXTRA_CONFLICT_TERMS: tuple[str, ...] = (
    "slap",
    "punch",
    "hit",
    "shove",
    "kicked",
    "blocked",
    "unfollow",
    "subtweet",
    "drama",
    "beef",
    "feud",
    "lawsuit",
    "custody",
    "evict",
    "lease",
    "roommate",
    "neighbor",
    "boss",
    "hr",
    "quit",
    "walkout",
    "strike",
    "union",
    "harass",
    "stalk",
    "restraining",
    "911",
    "emergency",
    "hospital",
    "injury",
    "damage",
    "property",
    "money",
    "debt",
    "stealing",
    "blackmail",
    "extort",
)
_EXTRA_PAYOFF_TERMS: tuple[str, ...] = (
    "long story short",
    "tl dr",
    "tldr",
    "edit:",
    "update:",
    "edit 2",
    "edit2",
    "edit 3",
    "after thinking",
    "after reading comments",
    "top comment",
    "consensus",
    "we talked",
    "we broke up",
    "we made up",
    "i moved out",
    "i quit",
    "i apologized",
    "they apologized",
    "got a lawyer",
    "went to therapy",
    "cut contact",
    "no contact",
    "happy ending",
    "worst ending",
    "plot twist",
    "i was wrong",
    "i was right",
    "lesson learned",
    "never again",
    "still processing",
    "still angry",
    "still hurts",
    "years later",
    "months later",
    "weeks later",
    "the next day",
)

_BROWSER_USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.91 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.4; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.105 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_3 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) CriOS/123.0.6312.52 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Android 14; Mobile; rv:124.0) Gecko/124.0 Firefox/124.0",
    "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.82 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/120.0.6099.230 Mobile Safari/537.36",
] + list(_EXTRA_BROWSER_USER_AGENTS)

_REDDIT_SESSION = requests.Session()
_PROGRESS_ACTIVE = False
_INCOMPETECH_TRACK_CACHE: list[str] | None = None
_UA_PROVIDER: Any | None = None
_PIPELINE_T0: float | None = None
# Perf: avoid re-scanning music / re-probing durations / re-pruning DB every stage.
_FFPROBE_DURATION_CACHE: dict[str, tuple[int, float]] = {}
_LOCAL_MUSIC_SCAN_AT: float = 0.0
_LOCAL_MUSIC_PATHS: list[Path] = []
_LOCAL_MUSIC_TTL_SEC = 45.0
_FFMPEG_ENCODER_AVAILABLE: dict[str, bool] = {}
_USED_STORY_KEYS_CACHE: tuple[float, frozenset[str]] | None = None
_USED_STORY_KEYS_CACHE_TTL_SEC = 1.25
_RE_WS = re.compile(r"\s+")
_RE_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")
_RE_NONSPACE = re.compile(r"\S+")
_RE_SILENCE_START = re.compile(r"silence_start:\s*([0-9.]+)")
_RE_SILENCE_END = re.compile(r"silence_end:\s*([0-9.]+)")
_RE_INCOMPETECH_TRACK = re.compile(
    r"https://incompetech\.com/music/royalty-free/index\.html\?isrc=[A-Z0-9]+&Search=Search"
)
_RE_VIDEO_NUM = re.compile(r"video(\d+)\.mp4$", re.I)
_RE_RST_VIDEO_NUM = re.compile(r"rst(\d+)\.mp4$", re.I)
_RE_RSS_VIDEO_NUM = re.compile(r"rss(\d+)\.mp4$", re.I)
_RE_RSP_VIDEO_NUM = re.compile(r"rsp(\d+)\.mp4$", re.I)
_RE_RSX_VIDEO_NUM = re.compile(r"rsx(\d+)\.mp4$", re.I)
_RE_RSY_VIDEO_NUM = re.compile(r"rsy(\d+)\.mp4$", re.I)
_RE_RSZ_VIDEO_NUM = re.compile(r"rsz(\d+)\.mp4$", re.I)
_RE_RSW_VIDEO_NUM = re.compile(r"rsw(\d+)\.mp4$", re.I)
_RE_RSV_VIDEO_NUM = re.compile(r"rsv(\d+)\.mp4$", re.I)
_RE_RST2_VIDEO_NUM = re.compile(r"rst2(\d+)\.mp4$", re.I)
_RE_RSQ_VIDEO_NUM = re.compile(r"rsq(\d+)\.mp4$", re.I)
_RE_RSK_VIDEO_NUM = re.compile(r"rsk(\d+)\.mp4$", re.I)
_RE_RSM_VIDEO_NUM = re.compile(r"rsm(\d+)\.mp4$", re.I)
_RE_RSR_VIDEO_NUM = re.compile(r"rsr(\d+)\.mp4$", re.I)
_RE_RSH_VIDEO_NUM = re.compile(r"rsh(\d+)\.mp4$", re.I)
_RE_RSU_VIDEO_NUM = re.compile(r"rsu(\d+)\.mp4$", re.I)
_RE_RSV2_VIDEO_NUM = re.compile(r"rsv2(\d+)\.mp4$", re.I)
_RE_PTK2_VIDEO_NUM = re.compile(r"ptk2(\d+)\.mp4$", re.I)
_RE_RSA_VIDEO_NUM = re.compile(r"rsa(\d+)\.mp4$", re.I)
_RE_RSB_VIDEO_NUM = re.compile(r"rsb(\d+)\.mp4$", re.I)
_RE_RSE_VIDEO_NUM = re.compile(r"rse(\d+)\.mp4$", re.I)
_RE_RSN_VIDEO_NUM = re.compile(r"rsn(\d+)\.mp4$", re.I)
_RE_RSP2_VIDEO_NUM = re.compile(r"rsp2(\d+)\.mp4$", re.I)
_RE_ORL_VIDEO_NUM = re.compile(r"orl(\d+)\.mp4$", re.I)
_RE_RSL_VIDEO_NUM = re.compile(r"rsl(\d+)\.mp4$", re.I)
_RE_R3U_VIDEO_NUM = re.compile(r"r3u(\d+)\.mp4$", re.I)
_RE_SRT_ARROW = re.compile(r"(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})")
_SENTIMENT_POS_WORDS = (
    "love",
    "happy",
    "great",
    "amazing",
    "relief",
    "good",
    "better",
    "won",
    "success",
    "finally",
    "thankful",
) + _EXTRA_SENTIMENT_POS_WORDS
_SENTIMENT_NEG_WORDS = (
    "hate",
    "angry",
    "awful",
    "terrible",
    "anxious",
    "bad",
    "worse",
    "lost",
    "failure",
    "betrayed",
    "hurt",
) + _EXTRA_SENTIMENT_NEG_WORDS
_CONFLICT_TERMS = (
    "fight",
    "argument",
    "screamed",
    "yelled",
    "cheated",
    "divorce",
    "lied",
    "caught",
    "fired",
    "threatened",
    "revenge",
    "stole",
    "police",
    "accused",
    "toxic",
    "abuse",
) + _EXTRA_CONFLICT_TERMS
_PAYOFF_TERMS = (
    "in the end",
    "finally",
    "so i",
    "we decided",
    "update",
    "resolved",
    "lesson",
    "now",
    "after that",
    "turns out",
    "ended up",
    "conclusion",
) + _EXTRA_PAYOFF_TERMS

# RSX mode: generic checklist lines when keyword mapping does not fill all three slots.
_RSX_FLAG_FILLERS: tuple[str, ...] = (
    "Emotional reactions outrunning problem-solving",
    "Assumptions replacing direct communication",
    "No clear plan for repair or compromise",
    "Mixed signals that keep everyone guessing",
    "Scorekeeping instead of repairing the relationship",
    "Public performance replacing private honesty",
    "Urgency used to bypass consent and boundaries",
    "Guilt-trips framed as love or responsibility",
    "Comparisons to exes, friends, or idealized standards",
    "All-or-nothing framing that removes middle options",
    "Over-explaining to dodge accountability",
    "Minimizing impact after a serious breach of trust",
    "Promises without behavior change behind them",
    "Jealousy framed as care instead of control",
    "Financial secrecy paired with pressure to comply",
    "Weaponized incompetence around shared tasks",
    "Triangulation: pulling third parties into a two-person issue",
    "Threats to leave whenever conflict gets honest",
    "Rewriting history mid-argument to win the narrative",
    "Punishing withdrawal after you set a boundary",
    "Drama cycles that reset before real repair",
    "Hypervigilance that treats every talk like a trial",
    "Love-bombing right after a serious rupture",
    "Cold detachment used to regain control",
    "Public humiliation disguised as jokes",
    "Private demands that contradict public image",
    "Chronic lateness or broken plans without repair",
    "Expecting mind-reading instead of clear asks",
    "Moving goalposts whenever you meet a request",
    "Using kids, pets, or money as leverage",
)

# Broad topic → neutral insight lines. Merged into RS* narrators so more posts hit tailored text.
_BULK_STORY_INSIGHT_ROWS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("landlord", "lease", "evict", "rental", "tenant"), "Rent rules belong in writing before emotions run hot."),
    (("mortgage", "refinance", "closing", "escrow"), "Big money moments need patience, paper trails, and second reads."),
    (("roommate", "sublet", "deposit"), "Deposits and chores are relationship tests disguised as logistics."),
    (("car", "insurance", "accident", "collision", "deductible"), "After a crash, facts matter more than vibes."),
    (("wedding", "bride", "groom", "ceremony", "reception"), "Weddings compress family politics into one expensive day."),
    (("funeral", "grief", "mourning", "cemetery"), "Grief makes boundaries harder and more necessary."),
    (("pregnant", "pregnancy", "newborn", "baby", "infant"), "Sleep loss turns small conflicts into moral trials."),
    (("toddler", "teenager", "adolescent", "custody"), "Kids hear the subtext when adults fight in code."),
    (("school", "teacher", "principal", "homework", "grade"), "Academic stress often masks fear about the future."),
    (("college", "university", "professor", "tuition", "gpa"), "Higher ed conflicts mix money, identity, and ego."),
    (("scholarship", "fafsa", "student loan"), "Money for school feels personal even when it is systemic."),
    (("job interview", "resume", "linkedin", "recruiter"), "Hiring drama is often about risk, not your worth."),
    (("layoff", "fired", "severance", "unemployment"), "Job loss rewires how people hear tone."),
    (("promotion", "raise", "salary", "bonus"), "Pay conversations test whether respect is real."),
    (("remote", "wfh", "zoom", "slack", "teams"), "Remote work turns ambiguity into imagined slights."),
    (("startup", "cofounder", "equity", "vesting"), "Equity fights are future-you suing present-you."),
    (("legal", "lawyer", "lawsuit", "court", "subpoena"), "Legal language makes people defensive fast."),
    (("police", "911", "report", "arrest", "warrant"), "Involving authorities changes the story forever."),
    (("immigration", "visa", "green card", "citizenship"), "Paperwork stress spills into every relationship."),
    (("disability", "accommodation", "chronic", "pain"), "Invisible limits get dismissed by people who mean well."),
    (("therapy", "therapist", "psychiatrist", "meds"), "Care is not a debate trophy."),
    (("addiction", "sober", "rehab", "relapse", "aa"), "Recovery needs boundaries, not applause."),
    (("religion", "church", "mosque", "temple", "faith"), "Belief can comfort people or justify control."),
    (("politics", "election", "vote", "candidate"), "Politics turns loved ones into symbols."),
    (("military", "deployment", "veteran", "base"), "Distance and orders rewrite normal relationship rules."),
    (("neighbor", "hoa", "fence", "noise", "parking"), "Proximity makes courtesy feel optional until it is not."),
    (("hoa", "covenant", "fine"), "Rules feel petty until money is involved."),
    (("instagram", "tiktok", "facebook", "social media"), "Public performance changes private truth."),
    (("discord", "reddit", "online", "moderator"), "Online spaces reward the loudest version of you."),
    (("game", "gaming", "steam", "console", "raid"), "Games become serious when time and money stack up."),
    (("cheat", "cheating", "affair", "onlyfans"), "Betrayal rewires memory of the whole relationship."),
    (("dating", "hinge", "bumble", "tinder"), "Apps optimize novelty, not repair."),
    (("long distance", "ldr", "time zone"), "Distance turns reassurance into a full-time job."),
    (("ex", "exes", "coparent"), "Exes are co-managers of unfinished business."),
    (("inheritance", "will", "probate", "executor"), "Money from death makes fairness impossible and urgent."),
    (("tax", "irs", "audit", "refund"), "Tax stress makes people paranoid about paperwork."),
    (("credit", "score", "loan", "debt collector"), "Money shame makes honesty late."),
    (("hospital", "surgery", "diagnosis", "icu"), "Medical fear shrinks patience for everything else."),
    (("insurance", "claim", "denied", "premium"), "Insurance fights teach you what fine print means."),
    (("travel", "flight", "airport", "hotel", "vacation"), "Travel exposes compatibility under fatigue."),
    (("moving", "u-haul", "mover", "packing"), "Moving is a stress test with cardboard boxes."),
    (("pet", "dog", "cat", "vet", "shelter"), "Pets become proxies for who is responsible."),
    (("gym", "fitness", "trainer", "weight"), "Body talk is never neutral in relationships."),
    (("food", "diet", "vegan", "allergy"), "Food rules touch identity, culture, and control."),
    (("alcohol", "drunk", "bar", "wine"), "Drinking changes what people pretend they agreed to."),
    (("weed", "cannabis", "marijuana"), "Substance norms differ more than people admit."),
    (("phone", "iphone", "android", "password"), "Devices hold secrets and power."),
    (("hack", "password", "scam", "phishing"), "Tech fear makes trust expensive."),
    (("inherit", "family business", "partner"), "Work plus blood ties double the stakes."),
    (("contract", "nda", "noncompete"), "Paper promises outlive handshakes."),
    (("union", "strike", "boss", "hr"), "Workplace justice moves slow; anger moves fast."),
    (("overtime", "schedule", "shift"), "Time is the hidden currency of respect."),
    (("bully", "harass", "hostile"), "Silence often looks like consent from the outside."),
    (("racism", "sexism", "discrimination"), "Bias shows up as patterns, not one-liners."),
    (("assault", "abuse", "violence", "unsafe"), "Safety first is not negotiable, even when love is real."),
    (("stalk", "restraining", "threat"), "Fear changes what reasonable looks like."),
    (("kidnap", "missing", "amber"), "Crisis mode deletes nuance."),
    (("fire", "flood", "hurricane", "disaster"), "Disasters reveal who plans and who panics."),
    (("homeless", "eviction", "couch"), "Housing instability makes every choice urgent."),
    (("scholarship", "internship", "offer letter"), "Opportunity anxiety is still anxiety."),
    (("phd", "dissertation", "advisor"), "Academic power imbalances hide in mentorship language."),
    (("code", "github", "repo", "developer"), "Technical disagreements are often fear of being wrong."),
    (("ai", "chatgpt", "llm"), "New tools scare people who built identity on old rules."),
    (("nft", "crypto", "bitcoin"), "Money cults sound like community until cash moves."),
    (("wedding dress", "planner", "vendor"), "Vendors become accidental therapists."),
    (("bridesmaid", "groomsman", "best man"), "Wedding roles come with invisible invoices."),
    (("mother in law", "father in law", "in-law"), "In-laws are a second audience judging your choices."),
    (("sibling", "brother", "sister"), "Sibling history is a loaded dictionary."),
    (("stepmom", "stepdad", "stepparent", "blended"), "Blended families negotiate loyalty daily."),
    (("adopt", "adoption", "foster"), "Care systems add paperwork grief to emotional grief."),
    (("autism", "adhd", "neurodiver"), "Neurodivergence needs translation, not punishment."),
    (("burnout", "overwork", "quit"), "Burnout whispers before it screams."),
    (("panic", "anxiety", "attack"), "Anxiety makes certainty feel like oxygen."),
    (("depress", "suicide", "self harm"), "Dark thoughts need professional help, not hot takes."),
    (("elder", "nursing home", "caregiver"), "Aging parents reverse roles without a script."),
    (("will", "power of attorney", "medical proxy"), "Legal planning is love with signatures."),
    (("ring", "engagement", "proposal"), "Symbols carry weight far beyond their price."),
    (("divorce", "separate", "mediation"), "Separation is logistics wearing an emotional mask."),
    (("alimony", "child support"), "Support math feels moral even when it is legal."),
    (("car seat", "daycare", "nanny"), "Childcare is a schedule, a budget, and a trust fall."),
    (("affair", "emotional affair"), "Emotional affairs hide behind friendship labels."),
    (("open relationship", "poly", "polyamory"), "Non-monogamy needs rules sharper than monogamy's defaults."),
    (("kink", "bdsm", "consent"), "Consent is ongoing, specific, and revocable."),
    (("std", "sti", "test"), "Health privacy is dignity."),
    (("pregnant", "abortion", "miscarriage"), "Reproductive stakes are never abstract for the person living them."),
    (("ivf", "fertility"), "Fertility journeys turn calendars into emotional minefields."),
    (("surrogacy", "donor"), "Third parties complicate love stories with contracts."),
    (("racism", "slur"), "Language harm stacks."),
    (("immigrant", "deport", "ice"), "Immigration fear shrinks options."),
    (("visa", "sponsor"), "Sponsorship ties love to paperwork."),
    (("land", "property line", "survey"), "Dirt disputes are identity disputes."),
    (("tree", "roots", "branch"), "Nature law meets neighbor ego."),
    (("camera", "ring doorbell", "cctv"), "Surveillance changes trust math."),
    (("lawyer letter", "cease"), "Formal letters escalate faster than tone."),
    (("small claims", "mediation"), "Small courts still feel huge."),
    (("identity theft", "fraud", "chargeback"), "Financial crime makes you question everyone."),
    (("room", "closet", "bathroom"), "Space fights are respect fights."),
    (("thermostat", "electric", "utility"), "Utilities turn comfort into control."),
    (("split", "venmo", "paypal", "zelle"), "Apps make money transfers feel casual until they don't."),
    (("gift", "birthday", "christmas", "holiday"), "Gifts become scorecards when stress is high."),
    (("culture", "tradition", "custom"), "Tradition can be love or leverage depending on who enforces it."),
    (("language", "translate", "accent"), "Communication cost is higher than fluent people notice."),
    (("passport", "border", "customs"), "Borders add adrenaline to ordinary trips."),
    (("ticket", "speeding", "parking"), "Small citations feel like character judgments."),
    (("lawsuit", "defamation", "slander"), "Reputation fights are expensive emotionally."),
    (("nonprofit", "volunteer", "fundraiser"), "Good intentions still need boundaries."),
    (("church", "pastor", "congregation"), "Community care can become social surveillance."),
    (("military spouse", "pcs"), "Military moves erase local support networks fast."),
    (("gun", "firearm", "weapon"), "Safety conversations are non-optional."),
    (("knife", "threat", "weapon"), "Threats change what forgiveness means."),
    (("dorm", "roommate assignment"), "Random roommates are social experiments."),
    (("international", "student visa"), "Visa status makes normal risks feel existential."),
    (("plagiarism", "cheat on test", "academic integrity"), "Integrity fights are identity fights."),
    (("bully", "kid", "school"), "Kid cruelty mirrors adult power."),
    (("coach", "sport", "team"), "Sports drama is leadership drama in shorts."),
    (("reddit", "mod", "ban", "subreddit"), "Online moderation is power without eye contact."),
    (("discord mod", "server"), "Tiny kingdoms create real hurt feelings."),
    (("stream", "twitch", "chat"), "Audience pressure turns private jokes public."),
    (("youtube", "content", "monetize"), "Creators negotiate love and algorithm at once."),
    (("etsy", "small business", "shop"), "Small business owners wear every hat, including therapist."),
    (("amazon", "delivery", "package"), "Logistics fights are patience fights."),
    (("airbnb", "guest", "host"), "Hospitality apps turn homes into contracts."),
    (("uber", "lyft", "rideshare"), "Stranger danger meets customer service."),
    (("boss", "ceo", "founder"), "Titles change what silence means."),
    (("coworker", "team", "slack"), "Work friends blur lines easily."),
    (("client", "customer", "karen"), "Service jobs trade dignity for tips."),
    (("tip", "gratuity", "service"), "Money for manners is emotionally loaded."),
    (("inherit", "trust fund"), "Unearned money still feels earned in family stories."),
    (("prenup", "postnup"), "Contracts before love scare people who confuse care with risk."),
    (("affair", "snapchat"), "Ephemeral apps do not erase consequences."),
    (("revenge", "petty", "malicious"), "Revenge feels like justice until the bill arrives."),
    (("karma", "update", "edit"), "Updates rewrite how strangers judge you."),
    (("therapy", "couples counseling"), "Couples therapy fails when one person performs."),
    (("ghost", "ghosted", "blocked"), "Silence is a decision with a shape."),
    (("text", "dm", "message"), "Written words linger longer than tone."),
    (("call", "voicemail", "facetime"), "Voice adds context and pressure."),
    (("sleep", "insomnia", "snore"), "Sleep deprivation is a relationship solvent."),
    (("chore", "dishes", "laundry"), "Chores are respect made repetitive."),
    (("cook", "meal prep", "kitchen"), "Food labor is invisible until it stops."),
    (("clean", "mess", "hoard"), "Clean fights are control fights."),
    (("smell", "hygiene"), "Hygiene talks are shame landmines."),
    (("weight", "diet", "body"), "Bodies are not debate props."),
    (("hair", "tattoo", "piercing"), "Appearance autonomy is non-negotiable."),
    (("closet", "coming out"), "Coming out is safety math, not drama."),
    (("pronoun", "deadname", "misgender"), "Names are baseline respect."),
    (("racism", "microaggression"), "Small cuts still bleed."),
    (("sexism", "mansplain"), "Gender dynamics show up in meeting rooms and kitchens."),
    (("ableism", "accommodation"), "Access is not a favor."),
    (("class", "poor", "rich", "privilege"), "Money changes which risks feel optional."),
    (("car payment", "repo"), "Repo fear makes people cruel."),
    (("gamble", "casino", "bet"), "Gambling debt steals future trust."),
    (("crypto", "rug pull"), "Scams wear innovation costumes."),
    (("mlm", "pyramid"), "Recruitment love is not love."),
    (("cult", "guru", "coach"), "Charisma plus isolation is dangerous."),
    (("stalking", "ex keeps"), "Persistence is not romance when fear is present."),
    (("kid", "screens", "ipad"), "Screen rules are parenting philosophy fights."),
    (("dog bite", "leash", "park"), "Animal liability is human responsibility."),
    (("wedding", "plus one"), "Guest lists are budgets wearing etiquette."),
    (("funeral", "will reading"), "Death brings out the spreadsheet side of grief."),
    (("dna", "paternity", "23andme"), "Genetic surprises rewrite family scripts."),
    (("surprise party", "party"), "Surprises are not universally fun."),
    (("secret", "surprise", "hidden"), "Secrets scale fast in families."),
    (("lie", "lying", "lied"), "Lies are habits before they are events."),
    (("trust", "verify"), "Verification is not suspicion when stakes are high."),
    (("apology", "sorry", "forgive"), "Sorry without change is a soundtrack."),
    (("boundary", "limit", "no"), "No is a full sentence, even when it hurts."),
    (("ultimatum", "threat"), "Ultimatums work until they become wallpaper."),
    (("therapy", "journaling"), "Tools help when people use them honestly."),
    (("money", "split", "fair"), "Fair is a feeling dressed as math."),
    (("time", "priority", "busy"), "Busy is often a polite word for choice."),
    (("love", "care", "support"), "Love without action is a mood, not a plan."),
)

# When no keyword row hits, narrators pick randomly from these (per style).
_DEFAULT_RSY_FACT_FALLBACKS: tuple[str, ...] = (
    "Fact: Healthy outcomes usually come from boundaries, clarity, and follow-through.",
    "Fact: Most recurring fights are unspoken expectations wearing new costumes.",
    "Fact: Repair needs repetition, not a single perfect conversation.",
    "Fact: People hear intent less clearly when they feel unsafe.",
    "Fact: Clarity costs a little awkwardness; confusion costs a lot more.",
    "Fact: The fastest fix is rarely the most stable fix.",
    "Fact: Respect shows up in follow-through, not declarations.",
    "Fact: Assumptions age badly; agreements age better.",
    "Fact: Stress makes small problems look like character flaws.",
    "Fact: Listening is a skill, not a personality trait.",
    "Fact: Boundaries protect connection; absence of boundaries breeds resentment.",
    "Fact: Two truths can coexist without one canceling the other.",
)
_DEFAULT_RSZ_LESSON_FALLBACKS: tuple[str, ...] = (
    "Communicate expectations early and confirm them clearly.",
    "Put the important rules in writing before resentment writes them for you.",
    "Name the fear underneath the anger; it is easier to solve than the performance.",
    "Pick a small next step you can repeat, not a dramatic gesture you cannot sustain.",
    "Ask what success looks like on Tuesday, not just in theory.",
    "Separate the person from the pattern; patterns are fixable with structure.",
    "If it happens twice, it is a system problem, not a one-off.",
    "Calm timing matters as much as correct content.",
    "Assume good intent once, then verify with behavior.",
    "Protect sleep and food before you debate morality.",
    "Choose repair over winning when you want the relationship to survive.",
    "Document agreements while everyone is still friendly.",
)
_DEFAULT_RSV_ADVICE_FALLBACKS: tuple[str, ...] = (
    "Advice: clarify expectations, then choose the option with least long-term damage.",
    "Advice: slow down before you commit to a public confrontation.",
    "Advice: pick one boundary and state it plainly without a speech.",
    "Advice: ask for a specific behavior change, not a vibe shift.",
    "Advice: separate urgent feelings from urgent actions.",
    "Advice: choose the path you can live with if nothing about them changes.",
    "Advice: get one trusted outside perspective before you torch a bridge.",
    "Advice: write a short summary of facts before you argue about feelings.",
    "Advice: decide what you will stop doing, not only what they should do.",
    "Advice: protect your basics: housing, income, safety, and health.",
)
_DEFAULT_RSK_TAKEAWAY_FALLBACKS: tuple[str, ...] = (
    "Key takeaway: clear communication early usually prevents bigger damage later.",
    "Key takeaway: most repeat conflicts are hidden expectations with new costumes.",
    "Key takeaway: repair needs a plan, not a dramatic speech.",
    "Key takeaway: respect shows up in follow-through, not declarations.",
    "Key takeaway: boundaries are kindness with structure.",
    "Key takeaway: listen for fear underneath anger; fear needs different tools.",
    "Key takeaway: agreements beat vibes when stakes are high.",
    "Key takeaway: choose curiosity once before you choose certainty.",
)
_DEFAULT_RSM_MISTAKE_FALLBACKS: tuple[str, ...] = (
    "Avoid this mistake: choosing short-term relief over long-term stability.",
    "Avoid this mistake: negotiating while flooded so you concede too much.",
    "Avoid this mistake: assuming they understood what you never said plainly.",
    "Avoid this mistake: turning a specific issue into a global character verdict.",
    "Avoid this mistake: trying to win the argument instead of fixing the system.",
    "Avoid this mistake: ignoring patterns because the apology sounded sincere.",
    "Avoid this mistake: involving an audience before you involve a solution.",
)
_DEFAULT_RSR_REALITY_FALLBACKS: tuple[str, ...] = (
    "Reality check: short-term comfort often creates long-term problems.",
    "Reality check: feelings are real, but they are not always accurate reporters of risk.",
    "Reality check: you cannot negotiate with someone who denies the premise.",
    "Reality check: hope is not a strategy when the pattern is documented.",
    "Reality check: silence often gets misread as agreement.",
    "Reality check: love without boundaries becomes resentment.",
)
_DEFAULT_RSH_HARD_FALLBACKS: tuple[str, ...] = (
    "Hard truth: delaying hard conversations usually makes outcomes worse.",
    "Hard truth: being liked is cheaper than being respected, but respect lasts longer.",
    "Hard truth: someone can love you and still be unsafe for you.",
    "Hard truth: apologies without change are just emotional loans.",
    "Hard truth: you cannot outsource your boundaries to hints.",
    "Hard truth: fairness is a feeling; clarity is a tool.",
)
_DEFAULT_RSU_UNPOPULAR_FALLBACKS: tuple[str, ...] = (
    "Unpopular take: discomfort now is often cheaper than chaos later.",
    "Unpopular take: peace is not the absence of conflict; it is the presence of boundaries.",
    "Unpopular take: you are allowed to outgrow people who refuse to grow.",
    "Unpopular take: loyalty without standards becomes self-abandonment.",
    "Unpopular take: forgiveness does not require access.",
    "Unpopular take: some relationships survive only with distance.",
)
_DEFAULT_RSV2_VERDICT_FALLBACKS: tuple[str, ...] = (
    "Verdict: choose the option with lower long-term cost.",
    "Verdict: protect safety and stability before pride.",
    "Verdict: if the pattern repeats, treat it as data, not an exception.",
    "Verdict: pick the path you can explain to future-you without cringing.",
    "Verdict: when in doubt, slow down commitments and speed up information.",
)
_DEFAULT_PTK2_COLD_FALLBACKS: tuple[str, ...] = (
    "Cold take: short-term peace often causes long-term cost.",
    "Cold take: vibes are not a substitute for agreements.",
    "Cold take: hope is not due diligence.",
    "Cold take: your peace is also your responsibility.",
    "Cold take: drama feels meaningful; systems feel boring — systems work.",
)
_DEFAULT_RSA_ACCOUNTABILITY_FALLBACKS: tuple[str, ...] = (
    "Accountability means choosing responsibility over excuses.",
    "Accountability means naming impact, not only intent.",
    "Accountability means repair plans with dates and behaviors.",
    "Accountability means stopping the story where you become the only victim.",
    "Accountability means doing the boring follow-through, not the dramatic apology.",
)
_DEFAULT_RSB_BOUNDARY_FALLBACKS: tuple[str, ...] = (
    "Boundary check: if it drains you repeatedly, it needs a rule.",
    "Boundary check: generosity without limits becomes expectation.",
    "Boundary check: your no is still valid if they feel surprised.",
    "Boundary check: access should match trust and consistency.",
    "Boundary check: protect your calendar like it is part of your health.",
)
_DEFAULT_RSE_EMPATHY_FALLBACKS: tuple[str, ...] = (
    "Empathy check: understanding feelings is not the same as accepting harm.",
    "Empathy check: hurt people can still cause hurt; both can be true.",
    "Empathy check: stress explains tone; it does not erase impact.",
    "Empathy check: validation is not agreement.",
    "Empathy check: compassion without boundaries becomes self-erasure.",
)
_DEFAULT_RSN_NEGOTIATION_FALLBACKS: tuple[str, ...] = (
    "Negotiation check: if terms are vague, conflict will repeat.",
    "Negotiation check: put deadlines on promises.",
    "Negotiation check: separate people from the problem on paper.",
    "Negotiation check: trade-offs need explicit naming.",
    "Negotiation check: silence is not consent in high-stakes talks.",
)
_DEFAULT_RSP2_SHIFT_FALLBACKS: tuple[str, ...] = (
    "Perspective shift: understanding motive can change strategy.",
    "Perspective shift: fear often wears anger as a costume.",
    "Perspective shift: control can look like care until you need autonomy.",
    "Perspective shift: everyone thinks they are the reasonable one.",
    "Perspective shift: context does not excuse harm, but it explains tension.",
)
_DEFAULT_RSL_LEVERAGE_FALLBACKS: tuple[str, ...] = (
    "Dark-psych check: identify what each side can actually enforce.",
    "Dark-psych check: watch for guilt as a steering wheel.",
    "Dark-psych check: urgency is a common manipulation shortcut.",
    "Dark-psych check: confusion can be maintained on purpose.",
    "Dark-psych check: social pressure is leverage without a contract.",
)

# Rotating script shells so the same story type does not always sound identical.
_VAR_RSS_OPENERS: tuple[str, ...] = (
    "Quick dilemma. Two sides. You decide.",
    "Two versions of the same moment. Pick a lane.",
    "AITA energy, compressed. Side A, Side B.",
    "Same story, two readings. You be the judge.",
    "Dilemma mode: nobody is purely the hero here.",
    "Split-screen conflict. Who sounds more reasonable?",
)
_VAR_RSS_CTAS: tuple[str, ...] = (
    "Who is right? Comment A or B.",
    "Vote A or B and say what would change your mind.",
    "Drop A or B. Bonus: what rule would prevent round two?",
    "Comment A or B. Would you handle it differently?",
    "Pick A or B. Which side is underestimating the other?",
)
_VAR_RSP_OPENERS: tuple[str, ...] = (
    "Hot take alert.",
    "Unfiltered opinion incoming.",
    "Spicy but practical read on this one.",
    "Hot take, cold logistics.",
    "Opinion mode: disagree loudly if you need to.",
)
_VAR_RSP_CTAS: tuple[str, ...] = (
    "Do you agree or disagree? Comment your side.",
    "Agree, disagree, or partially? Comment.",
    "Where are you landing? Comment agree or disagree.",
    "Is this reasonable or rude? Comment your verdict.",
)
_VAR_RSX_OPENERS: tuple[str, ...] = (
    "Relationship red flag check. Three fast signals.",
    "Red flag radar. Three signals from one story.",
    "Quick scan: three warning patterns.",
    "Three relationship signals worth naming out loud.",
)
_VAR_RSX_CTAS: tuple[str, ...] = (
    "Would you stay or leave? Comment your call.",
    "Stay, leave, or repair-with-conditions? Comment.",
    "What is your hard no here? Comment below.",
)
_VAR_RSY_OPENERS: tuple[str, ...] = (
    "Myth versus fact. Quick reality check.",
    "Myth bust, one beat at a time.",
    "Reality check: myth first, then the fact.",
    "Quick myth versus fact on a messy human moment.",
)
_VAR_RSY_CTAS: tuple[str, ...] = (
    "Which part do people get wrong most? Comment below.",
    "What myth shows up in your life? Comment.",
    "Drop the myth you believed too long.",
)
_VAR_RSZ_OPENERS: tuple[str, ...] = (
    "One story. One lesson.",
    "Lesson mode: same mess, cleaner takeaway.",
    "What would you steal from this mistake?",
    "One takeaway you can actually use tomorrow.",
)
_VAR_RSZ_CTAS: tuple[str, ...] = (
    "What lesson would you add? Comment it.",
    "Comment the lesson you learned the hard way.",
    "What rule would you write after this? Comment.",
)
_VAR_RSW_OPENERS: tuple[str, ...] = (
    "What would you do in this situation?",
    "Choose your path. No perfect option.",
    "You are in the room. What do you do?",
    "Two moves, same pressure. Pick one.",
)
_VAR_RSW_CTAS: tuple[str, ...] = (
    "Comment A or B and why.",
    "A or B, plus what info you still need.",
    "Drop A or B. What would change your pick?",
)
_VAR_RSV_ACTIONS: tuple[str, ...] = (
    "Action step: pick one boundary and state it today.",
    "Action step: send one clarifying message without a speech.",
    "Action step: write three bullet facts before you reply emotionally.",
    "Action step: schedule the hard talk for when you are fed and rested.",
    "Action step: choose the smallest repair move you can repeat.",
)
_VAR_RSV_CTAS: tuple[str, ...] = (
    "Need part two? Comment it.",
    "Want a deeper playbook? Comment your scenario.",
    "Comment if you want a follow-up angle.",
)
_VAR_RST2_BEATS: tuple[str, ...] = (
    "After that: consequences start stacking up.",
    "Then: pressure builds and options shrink.",
    "Next: small choices start to compound.",
    "After that: everyone picks a side, wanted or not.",
)
_VAR_RST2_CTAS: tuple[str, ...] = (
    "What would you do at minute zero?",
    "If you could rewind one minute, what changes?",
    "Where would you intervene first? Comment.",
)
_VAR_RSQ_CTAS: tuple[str, ...] = (
    "Would you ignore this red flag? Comment yes or no.",
    "Is this line a dealbreaker? Comment yes or no.",
    "Would you trust someone who said this? Comment.",
)
_VAR_RSK_CTAS: tuple[str, ...] = (
    "Do you agree with this takeaway? Comment yes or no.",
    "Is this takeaway too soft, too harsh, or fair? Comment.",
    "Would you apply this takeaway in your life? Comment.",
)
_VAR_RSM_CTAS: tuple[str, ...] = (
    "Have you seen this mistake before? Comment it.",
    "What mistake did you almost make here? Comment.",
    "Tag the mistake you see most often.",
)
_VAR_RSR_CTAS: tuple[str, ...] = (
    "Do you agree with this reality check? Comment below.",
    "Too harsh or accurate? Comment.",
    "Reality check: agree or push back? Comment.",
)
_VAR_RSH_CTAS: tuple[str, ...] = (
    "Do you agree with this hard truth? Comment yes or no.",
    "Hard truth: fair or unfair? Comment.",
    "Is this truth useful, or just mean? Comment.",
)
_VAR_RSU_CTAS: tuple[str, ...] = (
    "Would this offend people, or is it true? Comment below.",
    "Unpopular but wise, or just rude? Comment.",
    "Where do you draw the line on this take? Comment.",
)
_VAR_RSV2_CTAS: tuple[str, ...] = (
    "Agree with the verdict? Comment yes or no.",
    "Would you overturn this verdict? Comment.",
    "Split decision? Comment your alternate ruling.",
)
_VAR_PTK2_CTAS: tuple[str, ...] = (
    "Too harsh, or accurate? Comment below.",
    "Cold but fair? Comment your read.",
    "Is this take useful or just cynical? Comment.",
)
_VAR_RSA_CTAS: tuple[str, ...] = (
    "Who needs to own this? Comment your take.",
    "Where does accountability actually belong? Comment.",
    "Name the missing apology. Comment.",
)
_VAR_RSB_CTAS: tuple[str, ...] = (
    "Would you set this boundary? Comment yes or no.",
    "Is this boundary too strict? Comment.",
    "What boundary is missing here? Comment.",
)
_VAR_RSE_CTAS: tuple[str, ...] = (
    "Can both sides be hurt here? Comment your take.",
    "Where is empathy warranted, and where is it not? Comment.",
    "Who deserves grace here? Comment.",
)
_VAR_RSN_CTAS: tuple[str, ...] = (
    "Would this solve it, or not enough? Comment below.",
    "What term is still missing? Comment.",
    "Would you sign this deal? Comment yes or no.",
)
_VAR_RSP2_CTAS: tuple[str, ...] = (
    "Does this change your view? Comment yes or no.",
    "Did your angle shift at all? Comment.",
    "Still Team Original Story? Comment.",
)
_VAR_ORL_CTAS: tuple[str, ...] = (
    "Is this the right frame? Comment your view.",
    "What frame fits better? Comment.",
    "Reframe this in one sentence. Comment.",
)
_VAR_RSL_CTAS: tuple[str, ...] = (
    "Which tactic do you spot first? Comment below.",
    "Name the leverage move. Comment.",
    "What would you neutralize first? Comment.",
)
_VAR_R3U_HOOKS: tuple[str, ...] = (
    "Three things you probably never knew about {obj}.",
    "Wait, your {obj} can do this?",
    "Quick brain snack: three hidden facts about {obj}.",
    "Most people miss these three facts about {obj}.",
    "Your {obj} is way weirder than it looks.",
)
_VAR_R3U_CTAS: tuple[str, ...] = (
    "Comment the object you want next.",
    "Want part two with another everyday object? Comment it.",
    "Drop your favorite ordinary object for the next one.",
    "If this surprised you, follow for more quick facts.",
    "Comment one object everyone ignores.",
)
R3U_OBJECT_POOL: tuple[str, ...] = (
    "zipper",
    "mirror",
    "elevator",
    "stapler",
    "toothbrush",
    "keyboard",
    "umbrella",
    "microwave",
    "headphones",
    "backpack",
    "paper clip",
    "sneaker",
    "coffee mug",
    "light switch",
    "door handle",
)
_VAR_RST_INTROS: tuple[str, ...] = (
    "Today in history, {stamp}.",
    "History drop: {stamp}.",
    "On this date: {stamp}.",
    "Calendar check: {stamp}.",
)
_VAR_RST_OUTROS: tuple[str, ...] = (
    "Follow for tomorrow's history drop.",
    "Same time tomorrow for another date in history.",
    "Tap in tomorrow for the next history beat.",
)
_DEFAULT_RSW_PAIR_FALLBACKS: tuple[tuple[str, str], ...] = (
    ("choose direct communication", "choose short-term comfort"),
    ("name the issue calmly", "keep peace and absorb the cost"),
    ("set a boundary with consequences", "give another chance without structure"),
    ("pause until you are regulated", "respond immediately while heated"),
    ("ask for mediation or a neutral third party", "keep it private and hope it resolves"),
    ("document and escalate professionally", "vent and risk reputational fallout"),
    ("offer a specific repair plan", "accept apologies without changed behavior"),
    ("protect your mental health first", "prioritize keeping the group together"),
    ("leave the situation cleanly", "stay and fight for control"),
)
_RSS_SIDE_B_DEFAULTS: tuple[str, ...] = (
    "the other side says your response was too harsh for the situation",
    "the other side says you made it about winning, not fixing",
    "the other side says you assumed intent without checking",
    "the other side says you went public before going private",
    "the other side says you minimized their stress to make your point",
    "the other side says you moved the goalposts mid-argument",
    "the other side says you punished them for being honest",
    "the other side says you treated a symptom and ignored the cause",
    "the other side says you used fairness language to dodge responsibility",
    "the other side says you heard attack when they asked for help",
    "the other side says you turned a request into a referendum on your character",
    "the other side says you escalated tone before clarifying facts",
    "the other side says you made them guess what you needed",
    "the other side says you kept score instead of solving",
    "the other side says you confused discomfort with danger",
)


def _export_star(name: str) -> bool:
    """Names exported via star-import from this module (underscore-prefixed included)."""
    if name == "__version__":
        return True
    if name.startswith("__") and name.endswith("__"):
        return False
    return True


__all__ = tuple(sorted(k for k in globals() if k != "_export_star" and _export_star(k)))
del _export_star
